; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html



[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino

; (선택) Flash/PSRAM 크기 설정 - XH-S3E가 16MB Flash / 8MB PSRAM인 경우
; board_build.flash_size = 16MB

upload_port = COM8
monitor_port = COM8
; upload_port = COM18
; monitor_port = COM18

board_build.arduino.usb_cdc_enabled = true
board_build.arduino.serial_disabled = false

monitor_speed = 115200

board_build.partitions = huge_app.csv



; 전코드
; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino




; ; upload_port = COM18
; ; monitor_port = COM18
; monitor_speed = 115200

; lib_deps =
;   https://github.com/adafruit/Adafruit-PWM-Servo-Driver-Library.git

    